package com.hibernate.comics.pojo;
// Generated 17 nov 2022 20:49:01 by Hibernate Tools 5.5.7.Final

/**
 * Comics generated by hbm2java
 */
public class Comics implements java.io.Serializable {

	private int comicId;
	private String titulo;
	private Integer paginas;
	private String editorial;

	public Comics() {
	}

	public Comics(int comicId) {
		this.comicId = comicId;
	}

	public Comics(int comicId, String titulo, Integer paginas, String editorial) {
		this.comicId = comicId;
		this.titulo = titulo;
		this.paginas = paginas;
		this.editorial = editorial;
	}

	public int getComicId() {
		return this.comicId;
	}

	public void setComicId(int comicId) {
		this.comicId = comicId;
	}

	public String getTitulo() {
		return this.titulo;
	}

	public void setTitulo(String titulo) {
		this.titulo = titulo;
	}

	public Integer getPaginas() {
		return this.paginas;
	}

	public void setPaginas(Integer paginas) {
		this.paginas = paginas;
	}

	public String getEditorial() {
		return this.editorial;
	}

	public void setEditorial(String editorial) {
		this.editorial = editorial;
	}

}
